# Insect Detect - Custom Configuration Settings

# Source:   https://github.com/maxsitt/insect-detect
# License:  GNU GPLv3 (https://choosealicense.com/licenses/gpl-3.0/)
# Author:   Maximilian Sittinger (https://github.com/maxsitt)
# Docs:     https://maxsitt.github.io/insect-detect-docs/

# Use this custom config file for modifications (copy and create multiple configurations if needed)

# System settings
powermanager:
  enabled: true     # Disable if no power management board is connected
  model: wittypi    # Power management board model (options: wittypi, pijuice)
  charge_min: 20    # Minimum required battery charge level (%) to start/continue a recording
  charge_check: 30  # Time interval (seconds) for checking battery charge level during recording
oak:
  temp_max: 100     # Maximum allowed OAK chip temperature (°C) to continue a recording (< 105°C)
  temp_check: 30    # Time interval (seconds) for checking OAK chip temperature during recording
storage:
  disk_min: 1000    # Minimum required free disk space (MB) to start/continue a recording
  disk_check: 60    # Time interval (seconds) for checking free disk space during recording
logging:
  enabled: false    # Log system information (temperature, memory, CPU utilization, battery info)
  interval: 30      # Time interval (seconds) for saving logs during recording

# Camera settings
camera:
  fps: 20              # Camera frame rate (range: 1-30) -> higher fps increases power consumption
  resolution:          # Resolution of captured images (HQ frames)
    width: 3840        # Frame width (max. 3840) -> must be multiple of 32, e.g. 2176 for ~square
    height: 2160       # Frame height (max. 2160) -> must be multiple of 2
  jpeg_quality: 80     # JPEG quality of captured images (range: 0-100, recommended: 60-90)
  focus:
    mode: continuous   # Options: continuous, manual, range
    distance:
      enabled: true    # Use distance-based focus (in cm)
      manual: 19       # Manual focus position (distance to camera in cm)
      range:
        min: 15        # Minimum auto focus position (distance to camera in cm)
        max: 20        # Maximum auto focus position (distance to camera in cm)
    lens_position:
      enabled: false   # Use lens position-based focus (0-255)
      manual: 156      # Manual lens position (range: 0-255)
      range:
        min: 154       # Minimum lens position (range: 0-255) - greater distance to camera
        max: 165       # Maximum lens position (range: 0-255) - shorter distance to camera
  isp:
    sharpness: 1       # Image sharpness (range: 0-4) - setting to 0 can reduce artifacts
    luma_denoise: 1    # Luminance noise reduction (range: 0-4) - setting to 0 can reduce artifacts
    chroma_denoise: 1  # Chrominance noise reduction (range: 0-4)

# Recording settings
recording:
  duration:
    default: 60     # Duration (minutes) per recording session if powermanager is disabled
    battery:
      high: 60      # Duration (minutes) if battery charge level is > 70% or USB power is connected
      medium: 40    # Duration (minutes) if battery charge level is between 50-70%
      low: 20       # Duration (minutes) if battery charge level is between 30-50%
      minimal: 10   # Duration (minutes) if battery charge level is < 30%
  capture_interval:
    detection: 1.0  # Time interval (seconds) for saving HQ frame + metadata while object is detected
    timelapse: 600  # Time interval (seconds) for saving HQ frame (independent of detected objects)
  shutdown:
    enabled: true   # Shut down Raspberry Pi after recording session is finished or interrupted

# Detection settings
detection:
  model:
    weights: yolov5n_320_openvino_2022.1_4shave.blob  # Model weights file in "models" directory
    config: yolov5n_320_openvino_2022.1_4shave.json   # Model config file in "models" directory
  resolution:          # Resolution of downscaled + stretched/cropped LQ frames for model input
    width: 320         # Frame width
    height: 320        # Frame height
  conf_threshold: 0.5  # Confidence threshold (overrides model config file)
  iou_threshold: 0.5   # IoU threshold (overrides model config file)
  exposure_region:
    enabled: false     # Use bounding box coordinates from detections to set auto exposure region

# Post-processing settings
post_processing:    # Select post-processing methods (delete requires crop or overlay)
  crop:
    enabled: true   # Crop detections (= bounding boxes) from HQ frames
    method: square  # Crop method for detections/bounding boxes (options: square, original)
  overlay:
    enabled: false  # Draw overlays on HQ frame copies (bounding box, label, confidence, track ID)
  delete:
    enabled: false  # Delete original HQ frames with detections after processing
archive:
  enabled: false    # Archive (zip) all captured data + logs/configs and manage disk space
  disk_low: 5000    # Minimum required free disk space (MB) for unarchived data retention
upload:
  enabled: false    # Upload archived data to cloud storage provider (runs archive even if disabled)
  content: crop     # Select content for upload, always including metadata (options: all, full, crop, metadata)

# Web app settings
webapp:
  fps: 20           # Camera frame rate (range: 1-30) -> max. streamed fps depends on resolution
  resolution:       # Resolution of streamed HQ frames
    width: 1280     # Frame width (max. 1920) -> must be multiple of 32, e.g. 736 or 1088 for ~square
    height: 720     # Frame height (max. 1080) -> must be multiple of 2
  jpeg_quality: 70  # JPEG quality of streamed HQ frames (range: 0-100, recommended: 50-80)
  https:
    enabled: false  # Use HTTPS protocol (required for browser Geolocation API to get GPS coordinates)
